// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.xmg.learn.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xmg.learn.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.xmg.learn.proto.StudentResponse StudentResponse = 1;</code>
   */
  java.util.List<com.xmg.learn.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.xmg.learn.proto.StudentResponse StudentResponse = 1;</code>
   */
  com.xmg.learn.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.xmg.learn.proto.StudentResponse StudentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.xmg.learn.proto.StudentResponse StudentResponse = 1;</code>
   */
  java.util.List<? extends com.xmg.learn.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.xmg.learn.proto.StudentResponse StudentResponse = 1;</code>
   */
  com.xmg.learn.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
